[features]
seeds = false
skip-lint = false
[programs.localnet]
flipper = "HGefvbYCaNpJTLyFSEe5J9wpUdypxULS8Z7uS5ryK1PE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/jonathanfoo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
